# Building your deep neural network: Step by Step


Take home:
1. use non-linear units like ReLu to improve your model
2. Build a deeper neural network(with more than 1 hidden layer)
3. Implement an easy-to-use neural network class

# 1 Packages

* dnn_utils provides some necessary functions for this notebook
* testCase provides some test cases to assess the correctness of your functions
* np.random.seed(1) is used to keep all the random function calls consisten.

In [1]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
#from testCases import *
#from dnn_utils import sigmoid, sigmoid_backward, relu, relu_backward

# Outline of the Assignment

You will be implementing several "helper functions".
* Initialize the parameters for a two-layer netword and for an L-layer neural network
* Implement the forward propagation module
    * Complete the Linear part of a layer's forward propagation step
    * We give you the Activation function(relu/sigmoid)
    * Combine the previous two steps into a new linear-> activation forward cuntion
    

Note: for every forward function, there is a corresponding backward function. That's why we need to store some values in a cache. The cached values are useful for computing gradients.


# Initalization

two helper functions that will initialize the parameters for your model. The first function will be used to initalize parameters for a two layer model, the second will generalize this initialization process to L layers.

# 3.1 - 2-layer Neural Network

Exercise: Create and initialize the parameters of the 2-layer neural network

Instructions:
* The model's structure is: LINEAR -> RELU -> LINEAR -> SIGMOID
* Use random initialization for the weight matrices. Use np.random(shape)*0.01 with the corerect shape
* Use zero initialization for the biases. Use np.zeros(shape)

In [2]:
# Initialize parameters
def initialize_parameters(n_x, n_h, n_y):
    """
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    parameters -- python dictionary containing your parameters:
    W1 -- weight matrix of shape (n_h, n_x)
    b1 -- bias vector of shape (n_h, 1)
    W2 -- weight matrix of shape (n_y, n_h)
    b2 -- bias vector of shape (n_y, 1)
    
    """
    
    np.random.seed(1)
    
    W1 = np.random.randn(n_h, n_x)
    b1 = np.zeros(shape = (n_h, 1))
    W2 = np.random.randn(n_y, n_h)
    b2 = np.zeros(shape = (n_y, 1))
    
    assert(W1.shape == (n_h, n_x))
    assert(b1.shape == (n_h, 1))
    assert(W2.shape == (n_y, n_h))
    assert(b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                 "b1": b1,
                 "W2": W2,
                 "b2": b2}
    return parameters

In [3]:
parameters = initialize_parameters(2, 2, 1)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))


W1 = [[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
b1 = [[ 0.]
 [ 0.]]
W2 = [[ 0.86540763 -2.3015387 ]]
b2 = [[ 0.]]


3.2 L-layer Neural Network

In [6]:
# Initialize parameters deep
def initialize_parameters_deep(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the netword
    
    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], l))
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], l))
        
    return parameters



In [7]:
parameters = initialize_parameters_deep([5, 4, 3])
print("W1 = " + str(parameters["W1"]) )
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


# Forward propagation module

## Linear forward

forward propagation module.
Three functions in order:
* Linear
* Linear -> Activation where Activation will be eithre ReLU or sigmoid
* [Linear-> Relu] x (L - 1) -> Linear -> Sigmoid(whole model)


The linear forward module(vectorized over all examples) computes the following equations:

    Z[l] = W[l]A[l-1] + b[l]
    where A[0] = X
   

In [8]:
def linear_forward(A, W, b):
    Z = np.dot(W, A) + b
    
    assert(Z.shape == W.shape[0], A.shape[1])
    cache = (A, W, b)
    return Z, cache

In [ ]:
A, W, b = linea_forward_test_case()

Z, linear_cache = linear_forward(A, W, b)
print("Z = " + str(Z))

## 4.2 Linear-Activation Forward



In [10]:
def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation for the LINEAR->Activation layer
    
    Arguments:
    A_prev -- activations from previous layer(or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape(size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, l)
    
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu

    Returns:
    A -- the output of the activation function, also called the post-activation value
    cache -- a python dictionary contatining "linear_chace" and "activation_cache"
          -- stored for computing the backward pass efficiently
    """
    
    
    
    if activation == "sigmoid":
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
    
    elif activation == 'relu':
        Z, linear_cache = linear_forward(A, prev, W, b)
        A, activation_cache = relu(Z)
        
    assert(A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)
    
    return A, cache

In [ ]:
A_prev, W, b = linear_activation_forward_test_case()

A, linear_activation_cache = linear_activation_forward(A_prev, W, b, activation = "sigmoid")
print("With sigmoid: A  = " + str(A))

A, linear_activation_cache = linear_activation_forward(A_prev, W, b, activation = 'relu')
print("with Relu: A = str(A)")

## d) L-layer Model

For even more convenience when implementing L-layer Neural Net, you will need a function that replicates the previous one(linear_activation_forward with RELU) L - 1 times, then follows that with one linear_activation_forward with sigmoid



In [11]:
def L_model_forward(X, parameters):
    
    caches = []
    A = X
    L = len(parameters) // 2
    
    for l in range(1, L):
        A_prev = A
        A, cache = linear_activation_forward(A_prev, parameters['W' + str(l)],
                                            parameters['b' + str(1)],
                                            activation = 'relu')
        caches.append(cache)
        
    AL, cache = linear_activation_forward(A, parameters['W' + str(L)],
                                         parameters['b' + str(L)],
                                         activation = 'sigmoid')
    caches.append(cache)
    
    assert(AL.shape == (1, X.shape[l]))
    
    return AL, caches

In [ ]:
X, parameters = L_model_forward_test_case()
AL, caches = L_model_forward(X, parameters)
print("AL = " + str(AL))
print("Lenght of caches list = " + str(len(caches)))

## Cost function

In [12]:
def compute_lost(AL, Y):
    m = Y.shape[1]
    
    cost = (-1 / m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1 - Y, np.log(1 - AL)))
    
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    return cost

In [ ]:
Y, AL = compute_cost_test_case()

print("cost = " + str(compute_cost(AL, Y)))

# Backward prop

In [13]:
def linear_backward(dZ, cache):
    A_prev, W, b = cache
    m = A_prev.shape[1]
    
    dw = np.dot(dZ, cache[0].T)/m
    db = np.squeeze(np.sum(dZ, axis = 1, keepdims = True)) / m
    dA_prev = np.dot(cache[1].T, dZ)
    
    assert(dA_prev.shape == A_prev.shape)
    assert(dW.shape == W.shape)
    assert(isinstance(db, float))
    
    return dA_prev, dW, db



In [ ]:
dz, linear_cache = linear_backward_test_case()
dA_prev, dW, db = linear_backward(dZ, linear_cache)
print("dA_prev  = " + str(dA_prev))
print("dW = " + str(dW))
print("db = " + str(db))



## Linear activation backward


In [14]:
def linear_activation_backward(dA, cache, activation):
    linear_cache, activation_cache = cache
    
    if activation == "relu":
        dZ = relu_backward(dA, activation_cache)
        
    elif activation == 'sigmoid':
        dZ = sigmoid_backward(dA, activation_cache)
        
    dA_prev, dW, db = linear_backward(dZ, linear_cache)
    
    return dA_prev, dW, db

def linear_activation_backward(dA, cache, activation):
    linear_cache, activation_cache = cache